#index:
#    path: /
#    controller: App\Controller\DefaultController::index
select:
    path: /
    controller: App\Controller\Sql::select
div:
    path: /div
    controller: App\Controller\DivList::select
save:
    path: /save
    controller: App\Controller\Save::sql
edit:
    path: /edit
    controller: App\Controller\Edit::sql
delete:
    path: /delete
    controller: App\Controller\Delete::sql
adddiv:
    path: /adddiv
    controller: App\Controller\AddDiv::sql

