#index:
#    path: /
#    controller: App\Controller\DefaultController::index
select:
    path: /
    controller: App\Controller\Sql::select
div:
    path: /div
    controller: App\Controller\DivList::select

