<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYcjrwml\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYcjrwml/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYcjrwml.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYcjrwml\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYcjrwml\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ycjrwml',
    'container.build_id' => 'c2c75d49',
    'container.build_time' => 1592922704,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYcjrwml');
